### ISSUE TITLE
Blog post explanation, example and source don't match. 

### ISSUE THREAD

**Issue by ninnghazad** [jthomperoo/gjk-ts-implementation#1]
The drawings and coordinates in your blog post don't match the example calculations you made later in the post.

The blog post has a point of one of the triangles at [1,-1] whereas the code has it at [1,-2].

https://github.com/jthomperoo/gjk-ts-implementation/blob/1319ce6ef17b285fc1849ae6e056c349079aff49/src/index.ts#L62

The example in the blog post says it uses [1,-1] but values that are calculated are actually for the [1,-2].

(Also, nice post.)

**Comment by jthomperoo** [comment]
Hey, good catch! I'll fix that now, thanks!

**Comment by jthomperoo** [comment]
Ended up being a lot less work to just update the blog post!
Thanks again for pointing this out, fixed now :)
